### ISSUE TITLE
information: current status of the project?

### ISSUE THREAD

**Issue by PedroSFreitas** [Lifars/MantOS#16]
As the title implies, is the project still running? I saw that the last commit was in 2016.

**Comment by mbStavola** [comment]
While I'm no longer involved with the project, I'd just like to point out that even if it wasn't still running, it's pretty simple to maintain your own fork. Check out the [build guide](https://github.com/Lifars/MantOS/blob/master/BUILD.md), it should get you started.

Also, nice last name ;)

**Comment by PedroSFreitas** [comment]
**Thanks** for taking the time to answer.

To be honest, the idea was to contribute somehow. I think it's an interesting project that could benefit blue teams inside companies to take care of their network (but I know the scope and possible use cases of this project can go even beyond that).
But if the project is somewhat dead, I'm not sure if it would be a good idea to revive it alone since I'm part of another project that takes quite a lot of my time (BlackArch : https://blackarch.org/). On the other hand, if the project are still up and running, but slow, it'd be nice to help out.

ps: yeah, kinda funny. I think it's a common name in Europe (Portugal) :)

**Comment by mpiletskaya** [comment]
@PedroSFreitas  apologies that the answer took so long. The project was deprioritized for a while; and your issue triggered an official decision to be made. MantOS will continue to be on pause for undefined period of time. So the answer is yes, it's somewhat dead.

**Comment by PedroSFreitas** [comment]
@mpiletskaya Okay, thanks for you time.
